hl.on("hyprland.start", function ()
hl.exec_cmd("swaybg -o '*' -i ~/.config/hypr/wallpapers/cachyos-wallpapers/Skyscraper.png -m fill")
hl.exec_cmd("systemctl --user start hyprpolkitagent")
hl.exec_cmd("waybar")
hl.exec_cmd("fcitx5 -d")
hl.exec_cmd("mako")
hl.exec_cmd("bash -c 'mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown'")
hl.exec_cmd("systemctl --user start hyprpolkitagent")
hl.exec_cmd("steam")
hl.exec_cmd("vesktop --user-agent-os windows")
hl.exec_cmd("floorp")
hl.exec_cmd("copyq --start-server")
hl.exec_cmd("protonvpn-app")
hl.exec_cmd("qpwgraph")
hl.exec_cmd("~/.config/hypr/config/discord.sh --start-server")
-- Slow app launch fix
hl.exec_cmd("systemctl --user import-environment")
hl.exec_cmd("dbus-update-activation-environment --systemd")
hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY")
hl.exec_cmd("swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'")
hl.exec_cmd("ELECTRON_OZONE_PLATFORM_HINT=wayland")
end)
